// ALIS XML logical model -> FHIR profile mapping (transform direction: ALIS XML -> FHIR).
// Source codes are element ids of the logical model, target codes are element ids of the
// FHIR profile. Checked against input/fsh/mappings/alis-for-* and maps/Alis51toBundle.map.

Instance: Alis2FhirVisit
InstanceOf: ConceptMap
Title: "ALIS Visit to FHIR Mapping"
Description: "Mapping of the ALIS Visit logical model to the FHIR Encounter, Patient and ChargeItem profiles."
Usage: #definition
* status = #active
* experimental = false
* name = "Alis2FhirVisit"
* title = "ALIS Visit to FHIR Mapping"

// Visit -> CH ALIS Encounter
// >>> conceptmap-narrative-hotfix (generated by scripts/fix-conceptmap-narratives.py)
* text.status = #additional
* text.div = """
<div xmlns="http://www.w3.org/1999/xhtml"><a name="Alis2FhirVisit"> </a><a name="hcAlis2FhirVisit"> </a><p>Mapping from (not specified) to (not specified)</p><br/><p><b>Group 1 </b>Mapping from <a href="StructureDefinition-Visit.html">CH ALIS Leistungsschnittstelle - Visit</a> to <a href="StructureDefinition-ch-alis-connect-encounter.html">CH ALIS Encounter Profile</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-Visit.html#Visit">Visit</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-encounter-definitions.html#Encounter">Encounter</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Visit.html#Visit.VisitNumber">Visit.VisitNumber</a></td><td>1..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-encounter-definitions.html#Encounter.identifier.value">Encounter.identifier.value</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Visit.html#Visit.TerminationVisit">Visit.TerminationVisit</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-encounter-definitions.html#Encounter.extension:Termination">Encounter.extension:Termination</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Visit.html#Visit.TerminationReason">Visit.TerminationReason</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-encounter-definitions.html#Encounter.extension:Termination">Encounter.extension:Termination</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 2 </b>Mapping from <a href="StructureDefinition-Visit.html">CH ALIS Leistungsschnittstelle - Visit</a> to <a href="StructureDefinition-ch-alis-connect-patient.html">CH ALIS Patient Profile</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-Visit.html#Visit.PatientID">Visit.PatientID</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-patient-definitions.html#Patient.identifier:LocalPid.value">Patient.identifier:LocalPid.value</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Visit.html#Visit.PatientName">Visit.PatientName</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-patient-definitions.html#Patient.name.family">Patient.name.family</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Visit.html#Visit.PatientGivenName">Visit.PatientGivenName</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-patient-definitions.html#Patient.name.given">Patient.name.given</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Visit.html#Visit.PatientGender">Visit.PatientGender</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-patient-definitions.html#Patient.gender">Patient.gender</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Visit.html#Visit.PatientBirthDate">Visit.PatientBirthDate</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-patient-definitions.html#Patient.birthDate">Patient.birthDate</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 3 </b>Mapping from <a href="StructureDefinition-Visit.html">CH ALIS Leistungsschnittstelle - Visit</a> to <a href="StructureDefinition-ch-alis-connect-chargeitem.html">CH ALIS ChargeItem Profile</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-Visit.html#Visit.Service">Visit.Service</a></td><td>1..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem">ChargeItem</a></td><td>0..*</td><td>todo</td></tr></table></div>
"""
// <<< conceptmap-narrative-hotfix

* group[0].source = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/Visit"
* group[=].target = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/ch-alis-connect-encounter"
* group[=].element[0].code = #Visit
* group[=].element[=].target.code = #Encounter
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Visit.VisitNumber
* group[=].element[=].target.code = #Encounter.identifier.value
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Visit.TerminationVisit
* group[=].element[=].target.code = #Encounter.extension:Termination
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Visit.TerminationReason
* group[=].element[=].target.code = #Encounter.extension:Termination
* group[=].element[=].target.equivalence = #equivalent

// Visit -> CH ALIS Patient
* group[+].source = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/Visit"
* group[=].target = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/ch-alis-connect-patient"
* group[=].element[0].code = #Visit.PatientID
* group[=].element[=].target.code = #Patient.identifier:LocalPid.value
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Visit.PatientName
* group[=].element[=].target.code = #Patient.name.family
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Visit.PatientGivenName
* group[=].element[=].target.code = #Patient.name.given
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Visit.PatientGender
* group[=].element[=].target.code = #Patient.gender
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Visit.PatientBirthDate
* group[=].element[=].target.code = #Patient.birthDate
* group[=].element[=].target.equivalence = #equivalent

// Visit -> CH ALIS ChargeItem (each Service becomes one ChargeItem)
* group[+].source = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/Visit"
* group[=].target = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/ch-alis-connect-chargeitem"
* group[=].element[0].code = #Visit.Service
* group[=].element[=].target.code = #ChargeItem
* group[=].element[=].target.equivalence = #equivalent
