// ALIS XML logical model -> FHIR profile mapping (transform direction: ALIS XML -> FHIR).
// Checked against input/fsh/mappings/alis-for-ChAlisChargeItem.fsh and maps/Alis51toBundle.map.

Instance: Alis2FhirService
InstanceOf: ConceptMap
Title: "ALIS Service to FHIR Mapping"
Description: "Mapping of the ALIS Service logical model to the FHIR ChargeItem and Condition profiles."
Usage: #definition
* status = #active
* experimental = false
* name = "Alis2FhirService"
* title = "ALIS Service to FHIR Mapping"

// Service -> CH ALIS ChargeItem

// >>> conceptmap-narrative-hotfix (generated by scripts/fix-conceptmap-narratives.py)
* text.status = #additional
* text.div = """
<div xmlns="http://www.w3.org/1999/xhtml"><a name="Alis2FhirService"> </a><a name="hcAlis2FhirService"> </a><p>Mapping from (not specified) to (not specified)</p><br/><p><b>Group 1 </b>Mapping from <a href="StructureDefinition-Service.html">CH ALIS Leistungsschnittstelle - Service</a> to <a href="StructureDefinition-ch-alis-connect-chargeitem.html">CH ALIS ChargeItem Profile</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-Service.html#Service">Service</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem">ChargeItem</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.ServiceDate">Service.ServiceDate</a></td><td>1..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.occurrence[x]:occurrenceDateTime">ChargeItem.occurrence[x]:occurrenceDateTime</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.SessionID">Service.SessionID</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.extension:SessionID">ChargeItem.extension:SessionID</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.OrderID">Service.OrderID</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.extension:OrderID">ChargeItem.extension:OrderID</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.OrderDate">Service.OrderDate</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.extension:OrderDate">ChargeItem.extension:OrderDate</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.ReferrerID">Service.ReferrerID</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.costCenter.display">ChargeItem.costCenter.display</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.ServiceType">Service.ServiceType</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.code.coding.system">ChargeItem.code.coding.system</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.ServiceItem">Service.ServiceItem</a></td><td>1..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.code.coding.code">ChargeItem.code.coding.code</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.Form">Service.Form</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.extension:Form">ChargeItem.extension:Form</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.EnteredDateTime">Service.EnteredDateTime</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.enteredDate">ChargeItem.enteredDate</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.ProviderID">Service.ProviderID</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.performingOrganization.display">ChargeItem.performingOrganization.display</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.SectionCode">Service.SectionCode</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.extension:SectionCode">ChargeItem.extension:SectionCode</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.EnteredBy">Service.EnteredBy</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.enterer.display">ChargeItem.enterer.display</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.ItemNumber">Service.ItemNumber</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.extension:ItemNumber">ChargeItem.extension:ItemNumber</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.RefItemNumber">Service.RefItemNumber</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.extension:RefItemNumber">ChargeItem.extension:RefItemNumber</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.Quantity">Service.Quantity</a></td><td>1..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.quantity.value">ChargeItem.quantity.value</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.TPValue">Service.TPValue</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.extension:TPValue">ChargeItem.extension:TPValue</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.SessionSectionB">Service.SessionSectionB</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.extension:SessionAnnexB">ChargeItem.extension:SessionAnnexB</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.ServiceAssignment">Service.ServiceAssignment</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.extension:ServiceAssignment">ChargeItem.extension:ServiceAssignment</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.ServiceItemErrorCode">Service.ServiceItemErrorCode</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.extension:ServiceItemErrorCode">ChargeItem.extension:ServiceItemErrorCode</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.PersonV40">Service.PersonV40</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.performer">ChargeItem.performer</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Service.html#Service.ParameterV40">Service.ParameterV40</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.extension:ParameterV40">ChargeItem.extension:ParameterV40</a></td><td>0..*</td><td>todo</td></tr></table><hr/><p><b>Group 2 </b>Mapping from <a href="StructureDefinition-Service.html">CH ALIS Leistungsschnittstelle - Service</a> to <a href="StructureDefinition-ch-alis-connect-condition.html">CH ALIS Condition Profile</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-Service.html#Service.Diagnosis">Service.Diagnosis</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-condition-definitions.html#Condition">Condition</a></td><td>0..*</td><td>todo</td></tr></table></div>
"""
// <<< conceptmap-narrative-hotfix

* group[0].source = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/Service"
* group[=].target = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/ch-alis-connect-chargeitem"
* group[=].element[0].code = #Service
* group[=].element[=].target.code = #ChargeItem
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.ServiceDate
* group[=].element[=].target.code = #"ChargeItem.occurrence[x]:occurrenceDateTime"
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.SessionID
* group[=].element[=].target.code = #ChargeItem.extension:SessionID
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.OrderID
* group[=].element[=].target.code = #ChargeItem.extension:OrderID
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.OrderDate
* group[=].element[=].target.code = #ChargeItem.extension:OrderDate
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.ReferrerID
* group[=].element[=].target.code = #ChargeItem.costCenter.display
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.ServiceType
* group[=].element[=].target.code = #ChargeItem.code.coding.system
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.ServiceItem
* group[=].element[=].target.code = #ChargeItem.code.coding.code
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.Form
* group[=].element[=].target.code = #ChargeItem.extension:Form
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.EnteredDateTime
* group[=].element[=].target.code = #ChargeItem.enteredDate
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.ProviderID
* group[=].element[=].target.code = #ChargeItem.performingOrganization.display
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.SectionCode
* group[=].element[=].target.code = #ChargeItem.extension:SectionCode
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.EnteredBy
* group[=].element[=].target.code = #ChargeItem.enterer.display
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.ItemNumber
* group[=].element[=].target.code = #ChargeItem.extension:ItemNumber
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.RefItemNumber
* group[=].element[=].target.code = #ChargeItem.extension:RefItemNumber
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.Quantity
* group[=].element[=].target.code = #ChargeItem.quantity.value
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.TPValue
* group[=].element[=].target.code = #ChargeItem.extension:TPValue
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.SessionSectionB
* group[=].element[=].target.code = #ChargeItem.extension:SessionAnnexB
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.ServiceAssignment
* group[=].element[=].target.code = #ChargeItem.extension:ServiceAssignment
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.ServiceItemErrorCode
* group[=].element[=].target.code = #ChargeItem.extension:ServiceItemErrorCode
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.PersonV40
* group[=].element[=].target.code = #ChargeItem.performer
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Service.ParameterV40
* group[=].element[=].target.code = #ChargeItem.extension:ParameterV40
* group[=].element[=].target.equivalence = #equivalent

// Service.Diagnosis -> CH ALIS Condition (rendered as a contained Condition, referenced from Encounter.diagnosis)
* group[+].source = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/Service"
* group[=].target = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/ch-alis-connect-condition"
* group[=].element[0].code = #Service.Diagnosis
* group[=].element[=].target.code = #Condition
* group[=].element[=].target.equivalence = #equivalent
