// ALIS XML logical model -> FHIR profile mapping (transform direction: ALIS XML -> FHIR).
// Checked against input/fsh/mappings/alis-for-ChAlisCondition.fsh,
// alis-for-ChAlisExtensionDiagnosisConfidential.fsh and maps/Alis51toBundle.map.

Instance: Alis2FhirDiagnosis
InstanceOf: ConceptMap
Title: "ALIS Diagnosis to FHIR Mapping"
Description: "Mapping of the ALIS Diagnosis logical model to the FHIR Condition profile."
Usage: #definition
* status = #active
* experimental = false
* name = "Alis2FhirDiagnosis"
* title = "ALIS Diagnosis to FHIR Mapping"

// Diagnosis -> CH ALIS Condition
// >>> conceptmap-narrative-hotfix (generated by scripts/fix-conceptmap-narratives.py)
* text.status = #additional
* text.div = """
<div xmlns="http://www.w3.org/1999/xhtml"><a name="Alis2FhirDiagnosis"> </a><a name="hcAlis2FhirDiagnosis"> </a><p>Mapping from (not specified) to (not specified)</p><br/><p><b>Group 1 </b>Mapping from <a href="StructureDefinition-Diagnosis.html">CH ALIS Leistungsschnittstelle - Diagnosis</a> to <a href="StructureDefinition-ch-alis-connect-condition.html">CH ALIS Condition Profile</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-Diagnosis.html#Diagnosis.DiagnosisCode">Diagnosis.DiagnosisCode</a></td><td>1..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-condition-definitions.html#Condition.code.coding.code">Condition.code.coding.code</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Diagnosis.html#Diagnosis.DiagnosisSystem">Diagnosis.DiagnosisSystem</a></td><td>1..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-condition-definitions.html#Condition.code.coding.system">Condition.code.coding.system</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Diagnosis.html#Diagnosis.DiagnosisVersion">Diagnosis.DiagnosisVersion</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-condition-definitions.html#Condition.code.coding.version">Condition.code.coding.version</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Diagnosis.html#Diagnosis.DiagnosisConfidential">Diagnosis.DiagnosisConfidential</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-condition-definitions.html#Condition.extension:DiagnosisConfidential">Condition.extension:DiagnosisConfidential</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Diagnosis.html#Diagnosis.OnSetDateTime">Diagnosis.OnSetDateTime</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-condition-definitions.html#Condition.onset[x]:onsetDateTime">Condition.onset[x]:onsetDateTime</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-Diagnosis.html#Diagnosis.Laterality">Diagnosis.Laterality</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-condition-definitions.html#Condition.bodySite">Condition.bodySite</a></td><td>0..1</td><td>todo</td></tr></table></div>
"""
// <<< conceptmap-narrative-hotfix

* group[0].source = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/Diagnosis"
* group[=].target = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/ch-alis-connect-condition"
* group[=].element[0].code = #Diagnosis.DiagnosisCode
* group[=].element[=].target.code = #Condition.code.coding.code
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Diagnosis.DiagnosisSystem
* group[=].element[=].target.code = #Condition.code.coding.system
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Diagnosis.DiagnosisVersion
* group[=].element[=].target.code = #Condition.code.coding.version
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Diagnosis.DiagnosisConfidential
* group[=].element[=].target.code = #Condition.extension:DiagnosisConfidential
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Diagnosis.OnSetDateTime
* group[=].element[=].target.code = #"Condition.onset[x]:onsetDateTime"
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Diagnosis.Laterality
* group[=].element[=].target.code = #Condition.bodySite
* group[=].element[=].target.equivalence = #equivalent
