// ALIS XML logical model -> FHIR profile mapping (transform direction: ALIS XML -> FHIR).
// PersonV40 is nested in Service and rendered into ChargeItem.performer.
// Checked against input/fsh/mappings/alis-for-ChAlisChargeItem.fsh and maps/Alis51toBundle.map.

Instance: Alis2FhirPersonV40
InstanceOf: ConceptMap
Title: "ALIS PersonV40 to FHIR Mapping"
Description: "Mapping of the ALIS PersonV40 logical model to the FHIR ChargeItem.performer element."
Usage: #definition
* status = #active
* experimental = false
* name = "Alis2FhirPersonV40"
* title = "ALIS PersonV40 to FHIR Mapping"

// PersonV40 -> CH ALIS ChargeItem.performer
// >>> conceptmap-narrative-hotfix (generated by scripts/fix-conceptmap-narratives.py)
* text.status = #additional
* text.div = """
<div xmlns="http://www.w3.org/1999/xhtml"><a name="Alis2FhirPersonV40"> </a><a name="hcAlis2FhirPersonV40"> </a><p>Mapping from (not specified) to (not specified)</p><br/><p><b>Group 1 </b>Mapping from <a href="StructureDefinition-PersonV40.html">CH ALIS Leistungsschnittstelle - PersonV40</a> to <a href="StructureDefinition-ch-alis-connect-chargeitem.html">CH ALIS ChargeItem Profile</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-PersonV40.html#PersonV40">PersonV40</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.performer">ChargeItem.performer</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-PersonV40.html#PersonV40.PersonTyp">PersonV40.PersonTyp</a></td><td>1..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.performer.function.coding.code">ChargeItem.performer.function.coding.code</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-PersonV40.html#PersonV40.PersonID">PersonV40.PersonID</a></td><td>1..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-chargeitem-definitions.html#ChargeItem.performer.actor.display">ChargeItem.performer.actor.display</a></td><td>1..1</td><td>todo</td></tr></table></div>
"""
// <<< conceptmap-narrative-hotfix

* group[0].source = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/PersonV40"
* group[=].target = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/ch-alis-connect-chargeitem"
* group[=].element[0].code = #PersonV40
* group[=].element[=].target.code = #ChargeItem.performer
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #PersonV40.PersonTyp
* group[=].element[=].target.code = #ChargeItem.performer.function.coding.code
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #PersonV40.PersonID
* group[=].element[=].target.code = #ChargeItem.performer.actor.display
* group[=].element[=].target.equivalence = #equivalent
