// ALIS XML logical model -> FHIR profile mapping (transform direction: ALIS XML -> FHIR).
// ParameterV40 is nested in Service and rendered into the ChargeItem extension ParameterV40.
// Checked against input/fsh/mappings/alis-for-ChAlisExtensionParameterV40.fsh and maps/Alis51toBundle.map.

Instance: Alis2FhirParameterV40
InstanceOf: ConceptMap
Title: "ALIS ParameterV40 to FHIR Mapping"
Description: "Mapping of the ALIS ParameterV40 logical model to the FHIR ParameterV40 extension (on ChargeItem). Specific ParamTyp values (BMI, Billable, Amount, SLIndicationCode) are mapped to dedicated ChargeItem elements instead of the generic ParameterV40 extension."
Usage: #definition
* status = #active
* experimental = false
* name = "Alis2FhirParameterV40"
* title = "ALIS ParameterV40 to FHIR Mapping"

// ParameterV40 -> ch-alis-connect-ext-parameterv40

// >>> conceptmap-narrative-hotfix (generated by scripts/fix-conceptmap-narratives.py)
* text.status = #additional
* text.div = """
<div xmlns="http://www.w3.org/1999/xhtml"><a name="Alis2FhirParameterV40"> </a><a name="hcAlis2FhirParameterV40"> </a><p>Mapping from (not specified) to (not specified)</p><br/><p><b>Group 1 </b>Mapping from <a href="StructureDefinition-ParameterV40.html">CH ALIS Leistungsschnittstelle - ParameterV40</a> to <a href="StructureDefinition-ch-alis-connect-ext-parameterv40.html">CH ALIS Extension ParameterV40</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-ParameterV40.html#ParameterV40.ParamTyp">ParameterV40.ParamTyp</a></td><td>1..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-ext-parameterv40-definitions.html#Extension.extension:ParamTyp.value[x]:valueCodeableConcept">Extension.extension:ParamTyp.value[x]:valueCodeableConcept</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-ParameterV40.html#ParameterV40.ParamValue">ParameterV40.ParamValue</a></td><td>1..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-ext-parameterv40-definitions.html#Extension.extension:ParamValue.value[x]:valueString">Extension.extension:ParamValue.value[x]:valueString</a></td><td>1..1</td><td>todo</td></tr></table><hr/><p><b>Group 2 </b>Mapping from <a href="CodeSystem-ch-alis-connect-paramtyp.html">CH ALIS ParamTyp</a> to <a href="StructureDefinition-ch-alis-connect-chargeitem.html">CH ALIS ChargeItem Profile</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td></tr><tr><td>BMI</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td>ChargeItem.supportingInformation (ParameterV40: BMI)</td></tr><tr><td>Billable (Billable (j/n))</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td>ChargeItem.status (billable | not-billable)</td></tr><tr><td>Amount</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td>ChargeItem.priceOverride.value (ParameterV40: Amount)</td></tr><tr><td>SLIndicationCode (Indikationscode aus der SL (Spezialitätenliste))</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td>ChargeItem.extension:SLIndicationCode (ParameterV40: SLIndicationCode)</td></tr></table></div>
"""
// <<< conceptmap-narrative-hotfix

* group[0].source = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/ParameterV40"
* group[=].target = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/ch-alis-connect-ext-parameterv40"
* group[=].element[0].code = #ParameterV40.ParamTyp
* group[=].element[=].target.code = #"Extension.extension:ParamTyp.value[x]:valueCodeableConcept"
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #ParameterV40.ParamValue
* group[=].element[=].target.code = #"Extension.extension:ParamValue.value[x]:valueString"
* group[=].element[=].target.equivalence = #equivalent

// Specific ParamTyp values are mapped to dedicated ChargeItem elements instead of the generic ParameterV40 extension.
* group[+].source = "http://fhir.ch/ig/ch-alis-connect/CodeSystem/ch-alis-connect-paramtyp"
* group[=].target = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/ch-alis-connect-chargeitem"
* group[=].element[0].code = #BMI
* group[=].element[=].target.code = #ChargeItem.supportingInformation
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Billable
* group[=].element[=].target.code = #ChargeItem.status
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #Amount
* group[=].element[=].target.code = #ChargeItem.priceOverride.value
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #SLIndicationCode
* group[=].element[=].target.code = #ChargeItem.extension:SLIndicationCode
* group[=].element[=].target.equivalence = #equivalent
