// ALIS XML logical model -> FHIR profile mapping (transform direction: ALIS XML -> FHIR).
// ServiceAssignment is nested in Service and rendered into the ChargeItem extension ServiceAssignment.
// Checked against input/fsh/mappings/alis-for-ChAlisExtensionServiceAssignment.fsh and maps/Alis51toBundle.map.

Instance: Alis2FhirServiceAssignment
InstanceOf: ConceptMap
Title: "ALIS ServiceAssignment to FHIR Mapping"
Description: "Mapping of the ALIS ServiceAssignment logical model to the FHIR ServiceAssignment extension (on ChargeItem)."
Usage: #definition
* status = #active
* experimental = false
* name = "Alis2FhirServiceAssignment"
* title = "ALIS ServiceAssignment to FHIR Mapping"

// ServiceAssignment -> ch-alis-connect-ext-serviceassignment
// >>> conceptmap-narrative-hotfix (generated by scripts/fix-conceptmap-narratives.py)
* text.status = #additional
* text.div = """
<div xmlns="http://www.w3.org/1999/xhtml"><a name="Alis2FhirServiceAssignment"> </a><a name="hcAlis2FhirServiceAssignment"> </a><p>Mapping from (not specified) to (not specified)</p><br/><p><b>Group 1 </b>Mapping from <a href="StructureDefinition-ServiceAssignment.html">CH ALIS Leistungsschnittstelle - ServiceAssignment</a> to <a href="StructureDefinition-ch-alis-connect-ext-serviceassignment.html">CH ALIS Extension ServiceAssignment</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-ServiceAssignment.html#ServiceAssignment.OrderingProviderID">ServiceAssignment.OrderingProviderID</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-ext-serviceassignment-definitions.html#Extension.extension:OrderingProviderID.value[x]:valueString">Extension.extension:OrderingProviderID.value[x]:valueString</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-ServiceAssignment.html#ServiceAssignment.OrderSectionCode">ServiceAssignment.OrderSectionCode</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-ext-serviceassignment-definitions.html#Extension.extension:OrderSectionCode.value[x]:valueCoding">Extension.extension:OrderSectionCode.value[x]:valueCoding</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-ServiceAssignment.html#ServiceAssignment.OrderDate">ServiceAssignment.OrderDate</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-ext-serviceassignment-definitions.html#Extension.extension:OrderDate.value[x]:valueDateTime">Extension.extension:OrderDate.value[x]:valueDateTime</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-ServiceAssignment.html#ServiceAssignment.FollowUpOrder">ServiceAssignment.FollowUpOrder</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-ext-serviceassignment-definitions.html#Extension.extension:FollowUpOrder.value[x]:valueBoolean">Extension.extension:FollowUpOrder.value[x]:valueBoolean</a></td><td>1..1</td><td>todo</td></tr></table></div>
"""
// <<< conceptmap-narrative-hotfix

* group[0].source = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/ServiceAssignment"
* group[=].target = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/ch-alis-connect-ext-serviceassignment"
* group[=].element[0].code = #ServiceAssignment.OrderingProviderID
* group[=].element[=].target.code = #"Extension.extension:OrderingProviderID.value[x]:valueString"
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #ServiceAssignment.OrderSectionCode
* group[=].element[=].target.code = #"Extension.extension:OrderSectionCode.value[x]:valueCoding"
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #ServiceAssignment.OrderDate
* group[=].element[=].target.code = #"Extension.extension:OrderDate.value[x]:valueDateTime"
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #ServiceAssignment.FollowUpOrder
* group[=].element[=].target.code = #"Extension.extension:FollowUpOrder.value[x]:valueBoolean"
* group[=].element[=].target.equivalence = #equivalent
