// ALIS XML logical model -> FHIR profile mapping (transform direction: ALIS XML -> FHIR).
// SessionSectionB is nested in Service and rendered into the ChargeItem extension SessionAnnexB.
// Checked against input/fsh/mappings/alis-for-ChAlisExtensionSessionAnnexB.fsh and maps/Alis51toBundle.map.

Instance: Alis2FhirSessionSectionB
InstanceOf: ConceptMap
Title: "ALIS SessionSectionB to FHIR Mapping"
Description: "Mapping of the ALIS SessionSectionB logical model to the FHIR SessionAnnexB extension (on ChargeItem)."
Usage: #definition
* status = #active
* experimental = false
* name = "Alis2FhirSessionSectionB"
* title = "ALIS SessionSectionB to FHIR Mapping"

// SessionSectionB -> ch-alis-connect-ext-sessionannexb
// >>> conceptmap-narrative-hotfix (generated by scripts/fix-conceptmap-narratives.py)
* text.status = #additional
* text.div = """
<div xmlns="http://www.w3.org/1999/xhtml"><a name="Alis2FhirSessionSectionB"> </a><a name="hcAlis2FhirSessionSectionB"> </a><p>Mapping from (not specified) to (not specified)</p><br/><p><b>Group 1 </b>Mapping from <a href="StructureDefinition-SessionSectionB.html">CH ALIS Leistungsschnittstelle - SessionSectionB</a> to <a href="StructureDefinition-ch-alis-connect-ext-sessionannexb.html">CH ALIS Extension SessionAnnexB</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-SessionSectionB.html#SessionSectionB.SessionIDSectionB">SessionSectionB.SessionIDSectionB</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-ext-sessionannexb-definitions.html#Extension.extension:SessionIDSectionB.value[x]:valueUuid">Extension.extension:SessionIDSectionB.value[x]:valueUuid</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-SessionSectionB.html#SessionSectionB.AssignedSessionSectionB">SessionSectionB.AssignedSessionSectionB</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-alis-connect-ext-sessionannexb-definitions.html#Extension.extension:AssignedSessionSectionB.value[x]:valueUuid">Extension.extension:AssignedSessionSectionB.value[x]:valueUuid</a></td><td>0..1</td><td>todo</td></tr></table></div>
"""
// <<< conceptmap-narrative-hotfix

* group[0].source = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/SessionSectionB"
* group[=].target = "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/ch-alis-connect-ext-sessionannexb"
* group[=].element[0].code = #SessionSectionB.SessionIDSectionB
* group[=].element[=].target.code = #"Extension.extension:SessionIDSectionB.value[x]:valueUuid"
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #SessionSectionB.AssignedSessionSectionB
* group[=].element[=].target.code = #"Extension.extension:AssignedSessionSectionB.value[x]:valueUuid"
* group[=].element[=].target.equivalence = #equivalent
