Mapping: alis-for-ChAlisChargeItem
Id: alis
Title: "ALIS Mapping"
Description: "ALIS Mapping"
Source: ChAlisChargeItem
Target: "http://fhir.ch/ig/ch-alis-connect/StructureDefinition/Service"

* -> "Service"
* extension[ItemNumber] -> "ItemNumber"
* extension[RefItemNumber] -> "RefItemNumber"
* extension[SessionID] -> "SessionID"
* extension[OrderID] -> "OrderID"
* extension[OrderDate] -> "OrderDate"
* extension[SectionCode] -> "SectionCode"
* extension[TPValue] -> "TPValue"
* extension[Form] -> "Form"
* extension[ParameterV40] -> "ParameterV40"
* extension[SLIndicationCode] -> "ParameterV40.ParamTyp = SLIndicationCode"
* extension[SessionAnnexB] -> "SessionSectionB"
* extension[ServiceAssignment] -> "ServiceAssignment"
* extension[ServiceItemErrorCode] -> "ServiceItemErrorCode"
* status -> "ParameterV40.ParamTyp = Billable"
* code.coding.system -> "ServiceType"
* code.coding.code -> "ServiceItem"
* context -> "Visit"
* occurrenceDateTime -> "ServiceDate"
* performer -> "PersonV40"
* performer.function.coding.code -> "PersonTyp"
* performer.actor.display -> "PersonID"
* performingOrganization.display -> "ProviderID"
* costCenter.display -> "ReferrerID"
* quantity.value -> "Quantity"
* priceOverride.value -> "ParameterV40.ParamTyp = Amount"
* enterer.display -> "EnteredBy"
* enteredDate -> "EnteredDateTime"
* supportingInformation -> "ParameterV40.ParamTyp = BMI"